name: Trigger auto deployment for ac-agenda-dev-teste

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ac-agenda-dev-teste-AutoDeployTrigger-bb54d4c7-288d-491f-9749-6db6beeb7783.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAGENDADEVTESTE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: agendadevteste2.azurecr.io
          registryUsername: ${{ secrets.ACAGENDADEVTESTE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAGENDADEVTESTE_REGISTRY_PASSWORD }}
          containerAppName: ac-agenda-dev-teste
          resourceGroup: gp-agenda-dev-teste
          imageToBuild: agendadevteste2.azurecr.io/ac-agenda-dev-teste:${{ github.sha }}
          

     

